# Generated by Django 3.0.6 on 2024-09-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_alert', '0005_auto_20181103_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='givertransaction',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='givertransaction',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='None', max_length=4),
        ),
    ]
