# Generated by Django 3.0.6 on 2024-09-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_alert', '0007_auto_20240908_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='givertransaction',
            name='risk_transaction',
            field=models.BooleanField(default=False),
        ),
    ]
