# Generated by Django 3.0.6 on 2024-09-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_alert', '0008_givertransaction_risk_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='givertransaction',
            name='category',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='givertransaction',
            name='merchant',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='givertransaction',
            name='amount',
            field=models.FloatField(),
        ),
    ]
